name: faiadashu
description: Faiadashu FHIRDash - Build beautiful healthcare apps fast — use the Flutter™ SDK and follow the HL7® FHIR® standard.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.0
homepage: https://tiloc.github.io/faiadashu/
repository: https://github.com/tiloc/faiadashu
issue_tracker: https://github.com/tiloc/faiadashu/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0

  fhir: ^0.8.0
  # fhir_path: ^0.8.0
  fhir_path:
    git:
      url: https://github.com/phellowseven/fhir.git
      ref: main
      path: fhir_path
      # url: https://github.com/MayJuun/fhir.git
      # ref: fa9b061
      # path: fhir_path
    # path: ../fhir/fhir_path

  file_selector: ^0.9.5
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.0.2
  markdown: ^5.0.0
  meta: ^1.7.0
  mime: ^1.0.4
  scrollable_positioned_list: ^0.3.2
  simple_html_css: ^4.0.0
  webview_flutter: ^4.2.4
  webview_flutter_web: ^0.2.2+3

dev_dependencies:
  dart_code_metrics: ^4.15.0

  flutter_test:
    sdk: flutter

  lint: ^1.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
